### PR TITLE
[FW] c1

### PR DESCRIPTION
**Pull request by xmo-odoo**
Forward-Port-Of: odoo-mergebot-testing-org/ignore_proj_vK6-e6XL#1

### CODE REVIEW

**Comment by xmo-odoo** [comment]
[Pull request status dashboard](http://localhost:8069/odoo-mergebot-testing-org/ignore_proj_vK6-e6XL/pull/2).

**Comment by xmo-odoo** [comment]
@xmo-odoo @odoomergebotsacrifice-reviewer cherrypicking of pull request odoo-mergebot-testing-org/ignore_proj_vK6-e6XL#1 failed.

* b7436e642ca99af4f93724a1c7e678cb280ed66e <- on this commit
* 1492bee932f33709d85cb43b267f7e2ab008a3c2

stdout:
```
Auto-merging g
CONFLICT (add/add): Merge conflict in g

```

stderr:
```
08:44:11.070087 git.c:460               trace: built-in: git cherry-pick b7436e642ca99af4f93724a1c7e678cb280ed66e
error: could not apply b7436e6... c0
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by odoomergebotsacrifice-reviewer** [comment]
hansen r+

**Comment by xmo-odoo** [comment]
@xmo-odoo @odoomergebotsacrifice-reviewer unable to stage: All commits must have author and committer email, missing email on 2866e6386cf459f73b4e09d7e5fd642362259585 indicates the authorship is most likely incorrect.

**Pull request closed without merging**
